---
title: Prova... Rileva... Finally (istruzione)
description: Informazioni su come usare la gestione delle eccezioni con Visual Basic istruzioni try/catch/finally.
ms.date: 12/07/2018
f1_keywords:
- vb.Try...Catch...Finally
- vb.when
- vb.Finally
- vb.Catch
- vb.Try
helpviewer_keywords:
- Try...Catch...Finally statements
- Try statement [Visual Basic]
- try-catch exception handling, Try...Catch...Finally statements
- error handling, while running code
- Try statement [Visual Basic], Try...Catch...Finally
- Finally keyword [Visual Basic], Try...Catch...Finally
- Catch statement [Visual Basic]
- When keyword [Visual Basic]
- Visual Basic code, handling errors while running
- structured exception handling, Try...Catch...Finally statements
ms.assetid: d6488026-ccb3-42b8-a810-0d97b9d6472b
ms.openlocfilehash: bb6f17f7ce88caea0b9d30ec880194f2bb71c6a6
ms.sourcegitcommit: 5f236cd78cf09593c8945a7d753e0850e96a0b80
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 01/07/2020
ms.locfileid: "75705769"
---
# <a name="trycatchfinally-statement-visual-basic"></a><span data-ttu-id="1995e-103">Istruzione Try...Catch...Finally (Visual Basic)</span><span class="sxs-lookup"><span data-stu-id="1995e-103">Try...Catch...Finally Statement (Visual Basic)</span></span>

<span data-ttu-id="1995e-104">Consente di gestire alcuni o tutti i possibili errori che possono verificarsi in un blocco di codice specifico, mentre è ancora in esecuzione il codice.</span><span class="sxs-lookup"><span data-stu-id="1995e-104">Provides a way to handle some or all possible errors that may occur in a given block of code, while still running code.</span></span>

## <a name="syntax"></a><span data-ttu-id="1995e-105">Sintassi</span><span class="sxs-lookup"><span data-stu-id="1995e-105">Syntax</span></span>

```vb
Try
    [ tryStatements ]
    [ Exit Try ]
[ Catch [ exception [ As type ] ] [ When expression ]
    [ catchStatements ]
    [ Exit Try ] ]
[ Catch ... ]
[ Finally
    [ finallyStatements ] ]
End Try
```

## <a name="parts"></a><span data-ttu-id="1995e-106">Componenti</span><span class="sxs-lookup"><span data-stu-id="1995e-106">Parts</span></span>

|<span data-ttu-id="1995e-107">Termine</span><span class="sxs-lookup"><span data-stu-id="1995e-107">Term</span></span>|<span data-ttu-id="1995e-108">Definizione</span><span class="sxs-lookup"><span data-stu-id="1995e-108">Definition</span></span>|
|---|---|
|`tryStatements`|<span data-ttu-id="1995e-109">Parametro facoltativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-109">Optional.</span></span> <span data-ttu-id="1995e-110">Istruzioni in cui può verificarsi un errore.</span><span class="sxs-lookup"><span data-stu-id="1995e-110">Statement(s) where an error can occur.</span></span> <span data-ttu-id="1995e-111">Può essere un'istruzione composta.</span><span class="sxs-lookup"><span data-stu-id="1995e-111">Can be a compound statement.</span></span>|
|`Catch`|<span data-ttu-id="1995e-112">Parametro facoltativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-112">Optional.</span></span> <span data-ttu-id="1995e-113">Sono consentiti più blocchi di `Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-113">Multiple `Catch` blocks permitted.</span></span> <span data-ttu-id="1995e-114">Se si verifica un'eccezione durante l'elaborazione del blocco di `Try`, ogni istruzione `Catch` viene esaminata in ordine testuale per determinare se gestisce l'eccezione, con `exception` che rappresenta l'eccezione generata.</span><span class="sxs-lookup"><span data-stu-id="1995e-114">If an exception occurs when processing the `Try` block, each `Catch` statement is examined in textual order to determine whether it handles the exception, with `exception` representing the exception that has been thrown.</span></span>|
|`exception`|<span data-ttu-id="1995e-115">Parametro facoltativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-115">Optional.</span></span> <span data-ttu-id="1995e-116">Qualsiasi nome di variabile.</span><span class="sxs-lookup"><span data-stu-id="1995e-116">Any variable name.</span></span> <span data-ttu-id="1995e-117">Il valore iniziale di `exception` corrisponde al valore dell'errore generato.</span><span class="sxs-lookup"><span data-stu-id="1995e-117">The initial value of `exception` is the value of the thrown error.</span></span> <span data-ttu-id="1995e-118">Utilizzato con `Catch` per specificare l'errore rilevato.</span><span class="sxs-lookup"><span data-stu-id="1995e-118">Used with `Catch` to specify the error caught.</span></span> <span data-ttu-id="1995e-119">Se omesso, l'istruzione `Catch` intercetta qualsiasi eccezione.</span><span class="sxs-lookup"><span data-stu-id="1995e-119">If omitted, the `Catch` statement catches any exception.</span></span>|
|`type`|<span data-ttu-id="1995e-120">Parametro facoltativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-120">Optional.</span></span> <span data-ttu-id="1995e-121">Specifica il tipo di filtro di classe.</span><span class="sxs-lookup"><span data-stu-id="1995e-121">Specifies the type of class filter.</span></span> <span data-ttu-id="1995e-122">Se il valore di `exception` è del tipo specificato da `type` o di un tipo derivato, l'identificatore viene associato all'oggetto Exception.</span><span class="sxs-lookup"><span data-stu-id="1995e-122">If the value of `exception` is of the type specified by `type` or of a derived type, the identifier becomes bound to the exception object.</span></span>|
|`When`|<span data-ttu-id="1995e-123">Parametro facoltativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-123">Optional.</span></span> <span data-ttu-id="1995e-124">Un'istruzione `Catch` con una clausola `When` rileva le eccezioni solo quando `expression` restituisce `True`.</span><span class="sxs-lookup"><span data-stu-id="1995e-124">A `Catch` statement with a `When` clause catches exceptions only when `expression` evaluates to `True`.</span></span> <span data-ttu-id="1995e-125">Una clausola `When` viene applicata solo dopo avere verificato il tipo di eccezione e `expression` può fare riferimento all'identificatore che rappresenta l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="1995e-125">A `When` clause is applied only after checking the type of the exception, and `expression` may refer to the identifier representing the exception.</span></span>|
|`expression`|<span data-ttu-id="1995e-126">Parametro facoltativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-126">Optional.</span></span> <span data-ttu-id="1995e-127">Deve essere convertibile in modo implicito in `Boolean`.</span><span class="sxs-lookup"><span data-stu-id="1995e-127">Must be implicitly convertible to `Boolean`.</span></span> <span data-ttu-id="1995e-128">Qualsiasi espressione che descrive un filtro generico.</span><span class="sxs-lookup"><span data-stu-id="1995e-128">Any expression that describes a generic filter.</span></span> <span data-ttu-id="1995e-129">Usato in genere per filtrare in base al numero di errore.</span><span class="sxs-lookup"><span data-stu-id="1995e-129">Typically used to filter by error number.</span></span> <span data-ttu-id="1995e-130">Utilizzato con `When` parola chiave per specificare le circostanze in cui viene rilevato l'errore.</span><span class="sxs-lookup"><span data-stu-id="1995e-130">Used with `When` keyword to specify circumstances under which the error is caught.</span></span>|
|`catchStatements`|<span data-ttu-id="1995e-131">Parametro facoltativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-131">Optional.</span></span> <span data-ttu-id="1995e-132">Istruzioni per gestire gli errori che si verificano nel blocco `Try` associato.</span><span class="sxs-lookup"><span data-stu-id="1995e-132">Statement(s) to handle errors that occur in the associated `Try` block.</span></span> <span data-ttu-id="1995e-133">Può essere un'istruzione composta.</span><span class="sxs-lookup"><span data-stu-id="1995e-133">Can be a compound statement.</span></span>|
|`Exit Try`|<span data-ttu-id="1995e-134">Parametro facoltativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-134">Optional.</span></span> <span data-ttu-id="1995e-135">Parola chiave che si interrompe dalla struttura `Try...Catch...Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-135">Keyword that breaks out of the `Try...Catch...Finally` structure.</span></span> <span data-ttu-id="1995e-136">L'esecuzione riprende con il codice immediatamente successivo all'istruzione `End Try`.</span><span class="sxs-lookup"><span data-stu-id="1995e-136">Execution resumes with the code immediately following the `End Try` statement.</span></span> <span data-ttu-id="1995e-137">L'istruzione `Finally` verrà comunque eseguita.</span><span class="sxs-lookup"><span data-stu-id="1995e-137">The `Finally` statement will still be executed.</span></span> <span data-ttu-id="1995e-138">Non consentito nei blocchi di `Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-138">Not allowed in `Finally` blocks.</span></span>|
|`Finally`|<span data-ttu-id="1995e-139">Parametro facoltativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-139">Optional.</span></span> <span data-ttu-id="1995e-140">Un blocco `Finally` viene sempre eseguito quando l'esecuzione lascia una parte dell'istruzione `Try...Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-140">A `Finally` block is always executed when execution leaves any part of the `Try...Catch` statement.</span></span>|
|`finallyStatements`|<span data-ttu-id="1995e-141">Parametro facoltativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-141">Optional.</span></span> <span data-ttu-id="1995e-142">Istruzioni che vengono eseguite dopo l'elaborazione di tutti gli altri errori.</span><span class="sxs-lookup"><span data-stu-id="1995e-142">Statement(s) that are executed after all other error processing has occurred.</span></span>|
|`End Try`|<span data-ttu-id="1995e-143">Termina la struttura del `Try...Catch...Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-143">Terminates the `Try...Catch...Finally` structure.</span></span>|

## <a name="remarks"></a><span data-ttu-id="1995e-144">Note</span><span class="sxs-lookup"><span data-stu-id="1995e-144">Remarks</span></span>

<span data-ttu-id="1995e-145">Se si prevede che una particolare eccezione possa verificarsi durante una particolare sezione di codice, inserire il codice in un blocco `Try` e usare un blocco `Catch` per mantenere il controllo e gestire l'eccezione, se si verifica.</span><span class="sxs-lookup"><span data-stu-id="1995e-145">If you expect that a particular exception might occur during a particular section of code, put the code in a `Try` block and use a `Catch` block to retain control and handle the exception if it occurs.</span></span>

<span data-ttu-id="1995e-146">Un'istruzione `Try…Catch` è costituita da un blocco `Try` seguito da una o più clausole `Catch`, che specificano i gestori per varie eccezioni.</span><span class="sxs-lookup"><span data-stu-id="1995e-146">A `Try…Catch` statement consists of a `Try` block followed by one or more `Catch` clauses, which specify handlers for various exceptions.</span></span> <span data-ttu-id="1995e-147">Quando viene generata un'eccezione in un blocco di `Try`, Visual Basic cerca l'istruzione `Catch` che gestisce l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="1995e-147">When an exception is thrown in a `Try` block, Visual Basic looks for the `Catch` statement that handles the exception.</span></span> <span data-ttu-id="1995e-148">Se non viene trovata un'istruzione `Catch` corrispondente, Visual Basic esamina il metodo che ha chiamato il metodo corrente e così via fino allo stack di chiamate.</span><span class="sxs-lookup"><span data-stu-id="1995e-148">If a matching `Catch` statement is not found, Visual Basic examines the method that called the current method, and so on up the call stack.</span></span> <span data-ttu-id="1995e-149">Se non viene trovato alcun blocco `Catch`, Visual Basic Visualizza un messaggio di eccezione non gestita per l'utente e interrompe l'esecuzione del programma.</span><span class="sxs-lookup"><span data-stu-id="1995e-149">If no `Catch` block is found, Visual Basic displays an unhandled exception message to the user and stops execution of the program.</span></span>

<span data-ttu-id="1995e-150">In un'istruzione `Try…Catch` è possibile utilizzare più di un'istruzione `Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-150">You can use more than one `Catch` statement in a `Try…Catch` statement.</span></span> <span data-ttu-id="1995e-151">In tal caso, l'ordine delle clausole `Catch` è significativo perché vengono esaminate in ordine.</span><span class="sxs-lookup"><span data-stu-id="1995e-151">If you do this, the order of the `Catch` clauses is significant because they are examined in order.</span></span> <span data-ttu-id="1995e-152">Intercettare le eccezioni più specifiche prima di quelle meno specifiche.</span><span class="sxs-lookup"><span data-stu-id="1995e-152">Catch the more specific exceptions before the less specific ones.</span></span>

<span data-ttu-id="1995e-153">Le seguenti condizioni di istruzione `Catch` sono le meno specifiche e intercettano tutte le eccezioni derivate dalla classe <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="1995e-153">The following `Catch` statement conditions are the least specific, and will catch all exceptions that derive from the <xref:System.Exception> class.</span></span> <span data-ttu-id="1995e-154">In genere, è consigliabile usare una di queste varianti come ultimo blocco `Catch` nella struttura `Try...Catch...Finally`, dopo aver intercettato tutte le eccezioni specifiche previste.</span><span class="sxs-lookup"><span data-stu-id="1995e-154">You should ordinarily use one of these variations as the last `Catch` block in the `Try...Catch...Finally` structure, after catching all the specific exceptions you expect.</span></span> <span data-ttu-id="1995e-155">Il flusso di controllo non può mai raggiungere un blocco di `Catch` che segue una di queste varianti.</span><span class="sxs-lookup"><span data-stu-id="1995e-155">Control flow can never reach a `Catch` block that follows either of these variations.</span></span>

- <span data-ttu-id="1995e-156">Il `type` è `Exception`, ad esempio: `Catch ex As Exception`</span><span class="sxs-lookup"><span data-stu-id="1995e-156">The `type` is `Exception`, for example: `Catch ex As Exception`</span></span>

- <span data-ttu-id="1995e-157">L'istruzione non ha `exception` variabile, ad esempio: `Catch`</span><span class="sxs-lookup"><span data-stu-id="1995e-157">The statement has no `exception` variable, for example: `Catch`</span></span>

<span data-ttu-id="1995e-158">Quando un'istruzione `Try…Catch…Finally` è annidata in un altro blocco di `Try`, Visual Basic esamina prima di tutto `Catch` istruzione nel blocco di `Try` più interno.</span><span class="sxs-lookup"><span data-stu-id="1995e-158">When a `Try…Catch…Finally` statement is nested in another `Try` block, Visual Basic first examines each `Catch` statement in the innermost `Try` block.</span></span> <span data-ttu-id="1995e-159">Se non viene trovata alcuna istruzione `Catch` corrispondente, la ricerca procede con le istruzioni `Catch` del blocco `Try…Catch…Finally` esterno.</span><span class="sxs-lookup"><span data-stu-id="1995e-159">If no matching `Catch` statement is found, the search proceeds to the `Catch` statements of the outer `Try…Catch…Finally` block.</span></span>

<span data-ttu-id="1995e-160">Le variabili locali da un blocco di `Try` non sono disponibili in un blocco `Catch` perché sono blocchi separati.</span><span class="sxs-lookup"><span data-stu-id="1995e-160">Local variables from a `Try` block are not available in a `Catch` block because they are separate blocks.</span></span> <span data-ttu-id="1995e-161">Se si desidera utilizzare una variabile in più di un blocco, dichiarare la variabile all'esterno della struttura `Try...Catch...Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-161">If you want to use a variable in more than one block, declare the variable outside the `Try...Catch...Finally` structure.</span></span>

> [!TIP]
> <span data-ttu-id="1995e-162">L'istruzione `Try…Catch…Finally` è disponibile come frammento di codice IntelliSense.</span><span class="sxs-lookup"><span data-stu-id="1995e-162">The `Try…Catch…Finally` statement is available as an IntelliSense code snippet.</span></span> <span data-ttu-id="1995e-163">In Gestione frammenti di codice espandere modelli di **codice-if, for each, try catch, Property e così via**, quindi **gestione degli errori (eccezioni)** .</span><span class="sxs-lookup"><span data-stu-id="1995e-163">In the Code Snippets Manager, expand **Code Patterns - If, For Each, Try Catch, Property, etc**, and then **Error Handling (Exceptions)**.</span></span> <span data-ttu-id="1995e-164">Per altre informazioni, vedere [Code Snippets](/visualstudio/ide/code-snippets) (Frammenti di codice).</span><span class="sxs-lookup"><span data-stu-id="1995e-164">For more information, see [Code Snippets](/visualstudio/ide/code-snippets).</span></span>

## <a name="finally-block"></a><span data-ttu-id="1995e-165">Blocco finally</span><span class="sxs-lookup"><span data-stu-id="1995e-165">Finally block</span></span>

<span data-ttu-id="1995e-166">Se si dispone di una o più istruzioni che devono essere eseguite prima di uscire dalla struttura `Try`, utilizzare un blocco di `Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-166">If you have one or more statements that must run before you exit the `Try` structure, use a `Finally` block.</span></span> <span data-ttu-id="1995e-167">Il controllo passa al blocco `Finally` immediatamente prima che venga passato dalla struttura di `Try…Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-167">Control passes to the `Finally` block just before it passes out of the `Try…Catch` structure.</span></span> <span data-ttu-id="1995e-168">Questo vale anche se si verifica un'eccezione in qualsiasi punto all'interno della struttura `Try`.</span><span class="sxs-lookup"><span data-stu-id="1995e-168">This is true even if an exception occurs anywhere inside the `Try` structure.</span></span>

<span data-ttu-id="1995e-169">Un blocco `Finally` è utile per l'esecuzione di codice che deve essere eseguito anche se si verifica un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="1995e-169">A `Finally` block is useful for running any code that must execute even if there is an exception.</span></span> <span data-ttu-id="1995e-170">Il controllo viene passato al blocco `Finally` indipendentemente dalla modalità di uscita del blocco di `Try...Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-170">Control is passed to the `Finally` block regardless of how the `Try...Catch` block exits.</span></span>

<span data-ttu-id="1995e-171">Il codice in un blocco di `Finally` viene eseguito anche se il codice rileva un'istruzione `Return` in un blocco `Try` o `Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-171">The code in a `Finally` block runs even if your code encounters a `Return` statement in a `Try` or `Catch` block.</span></span> <span data-ttu-id="1995e-172">Il controllo non passa da un blocco `Try` o `Catch` al blocco `Finally` corrispondente nei casi seguenti:</span><span class="sxs-lookup"><span data-stu-id="1995e-172">Control does not pass from a `Try` or `Catch` block to the corresponding `Finally` block in the following cases:</span></span>

- <span data-ttu-id="1995e-173">Un' [istruzione End](end-statement.md) viene rilevata nel blocco `Try` o `Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-173">An [End Statement](end-statement.md) is encountered in the `Try` or `Catch` block.</span></span>

- <span data-ttu-id="1995e-174">Viene generata un'<xref:System.StackOverflowException> nel blocco `Try` o `Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-174">A <xref:System.StackOverflowException> is thrown in the `Try` or `Catch` block.</span></span>

<span data-ttu-id="1995e-175">Non è possibile trasferire in modo esplicito l'esecuzione in un blocco `Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-175">It is not valid to explicitly transfer execution into a `Finally` block.</span></span> <span data-ttu-id="1995e-176">Il trasferimento dell'esecuzione da un blocco di `Finally` non è valido, ad eccezione di un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="1995e-176">Transferring execution out of a `Finally` block is not valid, except through an exception.</span></span>

<span data-ttu-id="1995e-177">Se un'istruzione `Try` non contiene almeno un blocco di `Catch`, deve contenere un blocco di `Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-177">If a `Try` statement does not contain at least one `Catch` block, it must contain a `Finally` block.</span></span>

> [!TIP]
> <span data-ttu-id="1995e-178">Se non è necessario intercettare eccezioni specifiche, l'istruzione `Using` si comporta come un blocco di `Try…Finally` e garantisce l'eliminazione delle risorse, indipendentemente dalla modalità di uscita dal blocco.</span><span class="sxs-lookup"><span data-stu-id="1995e-178">If you do not have to catch specific exceptions, the `Using` statement behaves like a `Try…Finally` block, and guarantees disposal of the resources, regardless of how you exit the block.</span></span> <span data-ttu-id="1995e-179">Questo vale anche con un'eccezione non gestita.</span><span class="sxs-lookup"><span data-stu-id="1995e-179">This is true even with an unhandled exception.</span></span> <span data-ttu-id="1995e-180">Per altre informazioni, vedere [Istruzione using](using-statement.md).</span><span class="sxs-lookup"><span data-stu-id="1995e-180">For more information, see [Using Statement](using-statement.md).</span></span>

## <a name="exception-argument"></a><span data-ttu-id="1995e-181">Argomento Exception</span><span class="sxs-lookup"><span data-stu-id="1995e-181">Exception argument</span></span>

<span data-ttu-id="1995e-182">L'argomento `Catch` Block `exception` è un'istanza della classe <xref:System.Exception> o una classe che deriva dalla classe `Exception`.</span><span class="sxs-lookup"><span data-stu-id="1995e-182">The `Catch` block `exception` argument is an instance of the <xref:System.Exception> class or a class that derives from the `Exception` class.</span></span> <span data-ttu-id="1995e-183">L'istanza della classe `Exception` corrisponde all'errore che si è verificato nel blocco di `Try`.</span><span class="sxs-lookup"><span data-stu-id="1995e-183">The `Exception` class instance corresponds to the error that occurred in the `Try` block.</span></span>

<span data-ttu-id="1995e-184">Le proprietà dell'oggetto `Exception` consentono di identificare la ragione e la posizione di un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="1995e-184">The properties of the `Exception` object help to identify the cause and location of an exception.</span></span> <span data-ttu-id="1995e-185">Ad esempio, la proprietà <xref:System.Exception.StackTrace%2A> elenca i metodi chiamati che hanno generato l'eccezione, consentendo di individuare la posizione in cui si è verificato l'errore nel codice.</span><span class="sxs-lookup"><span data-stu-id="1995e-185">For example, the <xref:System.Exception.StackTrace%2A> property lists the called methods that led to the exception, helping you find where the error occurred in the code.</span></span> <span data-ttu-id="1995e-186"><xref:System.Exception.Message%2A> restituisce un messaggio in cui viene descritta l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="1995e-186"><xref:System.Exception.Message%2A> returns a message that describes the exception.</span></span> <span data-ttu-id="1995e-187"><xref:System.Exception.HelpLink%2A> restituisce un collegamento a un file della Guida associato.</span><span class="sxs-lookup"><span data-stu-id="1995e-187"><xref:System.Exception.HelpLink%2A> returns a link to an associated Help file.</span></span> <span data-ttu-id="1995e-188"><xref:System.Exception.InnerException%2A> restituisce l'oggetto `Exception` che ha causato l'eccezione corrente oppure restituisce `Nothing` se non sono presenti `Exception`originali.</span><span class="sxs-lookup"><span data-stu-id="1995e-188"><xref:System.Exception.InnerException%2A> returns the `Exception` object that caused the current exception, or it returns `Nothing` if there is no original `Exception`.</span></span>

## <a name="considerations-when-using-a-trycatch-statement"></a><span data-ttu-id="1995e-189">Considerazioni sull'utilizzo di un try... Istruzione catch</span><span class="sxs-lookup"><span data-stu-id="1995e-189">Considerations when using a Try…Catch statement</span></span>

<span data-ttu-id="1995e-190">Utilizzare un'istruzione `Try…Catch` solo per segnalare l'occorrenza di eventi di programma insoliti o imprevisti.</span><span class="sxs-lookup"><span data-stu-id="1995e-190">Use a `Try…Catch` statement only to signal the occurrence of unusual or unanticipated program events.</span></span> <span data-ttu-id="1995e-191">Di seguito sono riportati alcuni motivi:</span><span class="sxs-lookup"><span data-stu-id="1995e-191">Reasons for this include the following:</span></span>

- <span data-ttu-id="1995e-192">Il rilevamento delle eccezioni in fase di esecuzione comporta un sovraccarico aggiuntivo ed è probabilmente più lento rispetto al controllo preliminare per evitare eccezioni.</span><span class="sxs-lookup"><span data-stu-id="1995e-192">Catching exceptions at runtime creates additional overhead, and is likely to be slower than pre-checking to avoid exceptions.</span></span>

- <span data-ttu-id="1995e-193">Se un blocco di `Catch` non viene gestito correttamente, l'eccezione potrebbe non essere segnalata correttamente agli utenti.</span><span class="sxs-lookup"><span data-stu-id="1995e-193">If a `Catch` block is not handled correctly, the exception might not be reported correctly to users.</span></span>

- <span data-ttu-id="1995e-194">La gestione delle eccezioni rende un programma più complesso.</span><span class="sxs-lookup"><span data-stu-id="1995e-194">Exception handling makes a program more complex.</span></span>

<span data-ttu-id="1995e-195">Non è sempre necessaria un'istruzione `Try…Catch` per verificare la presenza di una condizione che potrebbe verificarsi.</span><span class="sxs-lookup"><span data-stu-id="1995e-195">You do not always need a `Try…Catch` statement to check for a condition that is likely to occur.</span></span> <span data-ttu-id="1995e-196">Nell'esempio seguente viene verificata l'esistenza di un file prima di tentare di aprirlo.</span><span class="sxs-lookup"><span data-stu-id="1995e-196">The following example checks whether a file exists before trying to open it.</span></span> <span data-ttu-id="1995e-197">In questo modo si riduce la necessità di intercettare un'eccezione generata dal metodo <xref:System.IO.File.OpenText%2A>.</span><span class="sxs-lookup"><span data-stu-id="1995e-197">This reduces the need for catching an exception thrown by the <xref:System.IO.File.OpenText%2A> method.</span></span>

[!code-vb[VbVbalrStatements#94](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#94)]

<span data-ttu-id="1995e-198">Verificare che il codice nei blocchi di `Catch` possa segnalare correttamente le eccezioni agli utenti, sia tramite la registrazione thread-safe che i messaggi appropriati.</span><span class="sxs-lookup"><span data-stu-id="1995e-198">Ensure that code in `Catch` blocks can properly report exceptions to users, whether through thread-safe logging or appropriate messages.</span></span> <span data-ttu-id="1995e-199">In caso contrario, le eccezioni potrebbero rimanere sconosciute.</span><span class="sxs-lookup"><span data-stu-id="1995e-199">Otherwise, exceptions might remain unknown.</span></span>

## <a name="async-methods"></a><span data-ttu-id="1995e-200">Metodi asincroni</span><span class="sxs-lookup"><span data-stu-id="1995e-200">Async methods</span></span>

<span data-ttu-id="1995e-201">Se si contrassegna un metodo con il modificatore [Async](../modifiers/async.md) , è possibile usare l'operatore [await](../operators/await-operator.md) nel metodo.</span><span class="sxs-lookup"><span data-stu-id="1995e-201">If you mark a method with the [Async](../modifiers/async.md) modifier, you can use the [Await](../operators/await-operator.md) operator in the method.</span></span> <span data-ttu-id="1995e-202">Un'istruzione con l'operatore `Await` sospende l'esecuzione del metodo fino al completamento dell'attività attesa.</span><span class="sxs-lookup"><span data-stu-id="1995e-202">A statement with the `Await` operator suspends execution of the method until the awaited task completes.</span></span> <span data-ttu-id="1995e-203">L'attività rappresenta il lavoro attualmente in fase di esecuzione.</span><span class="sxs-lookup"><span data-stu-id="1995e-203">The task represents ongoing work.</span></span> <span data-ttu-id="1995e-204">Quando l'attività associata all'operatore `Await` termina, l'esecuzione riprende nello stesso metodo.</span><span class="sxs-lookup"><span data-stu-id="1995e-204">When the task that's associated with the `Await` operator finishes, execution resumes in the same method.</span></span> <span data-ttu-id="1995e-205">Per altre informazioni, vedere [flusso di controllo in programmi asincroni](../../../visual-basic/programming-guide/concepts/async/control-flow-in-async-programs.md).</span><span class="sxs-lookup"><span data-stu-id="1995e-205">For more information, see [Control Flow in Async Programs](../../../visual-basic/programming-guide/concepts/async/control-flow-in-async-programs.md).</span></span>

<span data-ttu-id="1995e-206">Un'attività restituita da un metodo asincrono può terminare con uno stato di errore, a indicare che è stata completata a causa di un'eccezione non gestita.</span><span class="sxs-lookup"><span data-stu-id="1995e-206">A task returned by an Async method may end in a faulted state, indicating that it completed due to an unhandled exception.</span></span> <span data-ttu-id="1995e-207">Un'attività può inoltre terminare con uno stato annullato, il che comporta la generazione di un `OperationCanceledException` fuori dall'espressione await.</span><span class="sxs-lookup"><span data-stu-id="1995e-207">A task may also end in a canceled state, which results in an `OperationCanceledException` being thrown out of the await expression.</span></span> <span data-ttu-id="1995e-208">Per intercettare entrambi i tipi di eccezione, inserire l'espressione `Await` associata all'attività in un blocco di `Try` e intercettare l'eccezione nel blocco `Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-208">To catch either type of exception, place the `Await` expression that's associated with the task in a `Try` block, and catch the exception in the `Catch` block.</span></span> <span data-ttu-id="1995e-209">Un esempio è disponibile più avanti in questo argomento.</span><span class="sxs-lookup"><span data-stu-id="1995e-209">An example is provided later in this topic.</span></span>

<span data-ttu-id="1995e-210">Un'attività può essere in uno stato di errore perché più eccezioni erano responsabili dell'errore.</span><span class="sxs-lookup"><span data-stu-id="1995e-210">A task can be in a faulted state because multiple exceptions were responsible for its faulting.</span></span> <span data-ttu-id="1995e-211">Ad esempio, l'attività può essere il risultato di una chiamata a <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="1995e-211">For example, the task might be the result of a call to <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType>.</span></span> <span data-ttu-id="1995e-212">Quando si attende tale attività, l'eccezione rilevata è solo una delle eccezioni e non è possibile prevedere quale eccezione verrà rilevata.</span><span class="sxs-lookup"><span data-stu-id="1995e-212">When you await such a task, the caught exception is only one of the exceptions, and you can't predict which exception will be caught.</span></span> <span data-ttu-id="1995e-213">Un esempio è disponibile più avanti in questo argomento.</span><span class="sxs-lookup"><span data-stu-id="1995e-213">An example is provided later in this topic.</span></span>

<span data-ttu-id="1995e-214">Un'espressione `Await` non può trovarsi all'interno di un blocco di `Catch` o di `Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-214">An `Await` expression can't be inside a `Catch` block or `Finally` block.</span></span>

## <a name="iterators"></a><span data-ttu-id="1995e-215">Iterators</span><span class="sxs-lookup"><span data-stu-id="1995e-215">Iterators</span></span>

<span data-ttu-id="1995e-216">Una funzione iteratore o una funzione di accesso `Get` esegue un'iterazione personalizzata su una raccolta.</span><span class="sxs-lookup"><span data-stu-id="1995e-216">An iterator function or `Get` accessor performs a custom iteration over a collection.</span></span> <span data-ttu-id="1995e-217">Un iteratore usa un'istruzione [yield](yield-statement.md) per restituire ogni elemento della raccolta uno alla volta.</span><span class="sxs-lookup"><span data-stu-id="1995e-217">An iterator uses a [Yield](yield-statement.md) statement to return each element of the collection one at a time.</span></span> <span data-ttu-id="1995e-218">Si chiama una funzione iteratore usando un [per ogni... Istruzione successiva](for-each-next-statement.md).</span><span class="sxs-lookup"><span data-stu-id="1995e-218">You call an iterator function by using a [For Each...Next Statement](for-each-next-statement.md).</span></span>

<span data-ttu-id="1995e-219">Un'istruzione `Yield` può trovarsi all'interno di un blocco di `Try`.</span><span class="sxs-lookup"><span data-stu-id="1995e-219">A `Yield` statement can be inside a `Try` block.</span></span> <span data-ttu-id="1995e-220">Un blocco di `Try` contenente un'istruzione `Yield` può includere `Catch` blocchi e può disporre di un blocco `Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-220">A `Try` block that contains a `Yield` statement can have `Catch` blocks, and can have a `Finally` block.</span></span> <span data-ttu-id="1995e-221">Per un esempio, vedere la sezione "blocchi try in Visual Basic" degli [iteratori](../../programming-guide/concepts/iterators.md) .</span><span class="sxs-lookup"><span data-stu-id="1995e-221">See the "Try Blocks in Visual Basic" section of [Iterators](../../programming-guide/concepts/iterators.md) for an example.</span></span>

<span data-ttu-id="1995e-222">Un'istruzione `Yield` non può trovarsi all'interno di un blocco di `Catch` o di un blocco di `Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-222">A `Yield` statement cannot be inside a `Catch` block or a `Finally` block.</span></span>

<span data-ttu-id="1995e-223">Se il corpo del `For Each` (all'esterno della funzione iteratore) genera un'eccezione, un blocco di `Catch` nella funzione iteratore non viene eseguito, ma viene eseguito un blocco `Finally` nella funzione iteratore.</span><span class="sxs-lookup"><span data-stu-id="1995e-223">If the `For Each` body (outside of the iterator function) throws an exception, a `Catch` block in the iterator function is not executed, but a `Finally` block in the iterator function is executed.</span></span> <span data-ttu-id="1995e-224">Un blocco `Catch` all'interno di una funzione iteratore intercetta solo le eccezioni che si verificano all'interno della funzione iteratore.</span><span class="sxs-lookup"><span data-stu-id="1995e-224">A `Catch` block inside an iterator function catches only exceptions that occur inside the iterator function.</span></span>

## <a name="partial-trust-situations"></a><span data-ttu-id="1995e-225">Situazioni di attendibilità parziale</span><span class="sxs-lookup"><span data-stu-id="1995e-225">Partial-trust situations</span></span>

<span data-ttu-id="1995e-226">In situazioni di attendibilità parziale, ad esempio un'applicazione ospitata in una condivisione di rete, `Try...Catch...Finally` non rileva le eccezioni di sicurezza che si verificano prima che venga richiamato il metodo che contiene la chiamata.</span><span class="sxs-lookup"><span data-stu-id="1995e-226">In partial-trust situations, such as an application hosted on a network share, `Try...Catch...Finally` does not catch security exceptions that occur before the method that contains the call is invoked.</span></span> <span data-ttu-id="1995e-227">Nell'esempio seguente, quando lo si inserisce in una condivisione server e si esegue da questa posizione, viene generato l'errore "System. Security. SecurityException: request failed".</span><span class="sxs-lookup"><span data-stu-id="1995e-227">The following example, when you put it on a server share and run from there, produces the error "System.Security.SecurityException: Request Failed."</span></span> <span data-ttu-id="1995e-228">Per ulteriori informazioni sulle eccezioni di sicurezza, vedere la classe <xref:System.Security.SecurityException>.</span><span class="sxs-lookup"><span data-stu-id="1995e-228">For more information about security exceptions, see the <xref:System.Security.SecurityException> class.</span></span>

[!code-vb[VbVbalrStatements#85](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#85)]

<span data-ttu-id="1995e-229">In una situazione di attendibilità parziale, è necessario inserire l'istruzione `Process.Start` in un `Sub`separato.</span><span class="sxs-lookup"><span data-stu-id="1995e-229">In such a partial-trust situation, you have to put the `Process.Start` statement in a separate `Sub`.</span></span> <span data-ttu-id="1995e-230">La chiamata iniziale al `Sub` avrà esito negativo.</span><span class="sxs-lookup"><span data-stu-id="1995e-230">The initial call to the `Sub` will fail.</span></span> <span data-ttu-id="1995e-231">Questo consente `Try...Catch` di intercettarlo prima che venga avviata la `Sub` che contiene `Process.Start` e l'eccezione di sicurezza generata.</span><span class="sxs-lookup"><span data-stu-id="1995e-231">This enables `Try...Catch` to catch it before the `Sub` that contains `Process.Start` is started and the security exception produced.</span></span>

## <a name="examples"></a><span data-ttu-id="1995e-232">Esempi</span><span class="sxs-lookup"><span data-stu-id="1995e-232">Examples</span></span>

### <a name="the-structure-of-trycatchfinally"></a><span data-ttu-id="1995e-233">Struttura di try... Rileva... Infine</span><span class="sxs-lookup"><span data-stu-id="1995e-233">The structure of Try...Catch...Finally</span></span>

<span data-ttu-id="1995e-234">Nell'esempio seguente viene illustrata la struttura dell'istruzione `Try...Catch...Finally`.</span><span class="sxs-lookup"><span data-stu-id="1995e-234">The following example illustrates the structure of the `Try...Catch...Finally` statement.</span></span>

[!code-vb[VbVbalrStatements#86](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#86)]  

### <a name="exception-in-a-method-called-from-a-try-block"></a><span data-ttu-id="1995e-235">Eccezione in un metodo chiamato da un blocco try</span><span class="sxs-lookup"><span data-stu-id="1995e-235">Exception in a method called from a Try block</span></span>

<span data-ttu-id="1995e-236">Nell'esempio seguente il metodo `CreateException` genera un'`NullReferenceException`.</span><span class="sxs-lookup"><span data-stu-id="1995e-236">In the following example, the `CreateException` method throws a `NullReferenceException`.</span></span> <span data-ttu-id="1995e-237">Il codice che genera l'eccezione non si trova in un blocco `Try`.</span><span class="sxs-lookup"><span data-stu-id="1995e-237">The code that generates the exception is not in a `Try` block.</span></span> <span data-ttu-id="1995e-238">Pertanto, il metodo `CreateException` non gestisce l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="1995e-238">Therefore, the `CreateException` method does not handle the exception.</span></span> <span data-ttu-id="1995e-239">Il metodo `RunSample` gestisce l'eccezione perché la chiamata al metodo `CreateException` si trova in un blocco di `Try`.</span><span class="sxs-lookup"><span data-stu-id="1995e-239">The `RunSample` method does handle the exception because the call to the `CreateException` method is in a `Try` block.</span></span>

<span data-ttu-id="1995e-240">Nell'esempio sono incluse istruzioni `Catch` per diversi tipi di eccezioni, ordinate dal più specifico al più generale.</span><span class="sxs-lookup"><span data-stu-id="1995e-240">The example includes `Catch` statements for several types of exceptions, ordered from the most specific to the most general.</span></span>

[!code-vb[VbVbalrStatements#91](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#91)]

### <a name="the-catch-when-statement"></a><span data-ttu-id="1995e-241">Istruzione catch when</span><span class="sxs-lookup"><span data-stu-id="1995e-241">The Catch When statement</span></span>

<span data-ttu-id="1995e-242">Nell'esempio seguente viene illustrato come utilizzare un'istruzione `Catch When` per filtrare in un'espressione condizionale.</span><span class="sxs-lookup"><span data-stu-id="1995e-242">The following example shows how to use a `Catch When` statement to filter on a conditional expression.</span></span> <span data-ttu-id="1995e-243">Se l'espressione condizionale restituisce `True`, viene eseguito il codice nel blocco di `Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-243">If the conditional expression evaluates to `True`, the code in the `Catch` block runs.</span></span>

[!code-vb[VbVbalrStatements#92](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#92)]

### <a name="nested-try-statements"></a><span data-ttu-id="1995e-244">Istruzioni try nidificate</span><span class="sxs-lookup"><span data-stu-id="1995e-244">Nested Try statements</span></span>

<span data-ttu-id="1995e-245">Nell'esempio seguente è presente un'istruzione `Try…Catch` contenuta in un blocco di `Try`.</span><span class="sxs-lookup"><span data-stu-id="1995e-245">The following example has a `Try…Catch` statement that is contained in a `Try` block.</span></span> <span data-ttu-id="1995e-246">Il blocco `Catch` interno genera un'eccezione con la relativa proprietà `InnerException` impostata sull'eccezione originale.</span><span class="sxs-lookup"><span data-stu-id="1995e-246">The inner `Catch` block throws an exception that has its `InnerException` property set to the original exception.</span></span> <span data-ttu-id="1995e-247">Il blocco `Catch` esterno segnala la propria eccezione e l'eccezione interna.</span><span class="sxs-lookup"><span data-stu-id="1995e-247">The outer `Catch` block reports its own exception and the inner exception.</span></span>

[!code-vb[VbVbalrStatements#93](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#93)]

### <a name="exception-handling-for-async-methods"></a><span data-ttu-id="1995e-248">Gestione delle eccezioni per i metodi asincroni</span><span class="sxs-lookup"><span data-stu-id="1995e-248">Exception handling for async methods</span></span>

<span data-ttu-id="1995e-249">L'esempio seguente illustra la gestione delle eccezioni per i metodi asincroni.</span><span class="sxs-lookup"><span data-stu-id="1995e-249">The following example illustrates exception handling for async methods.</span></span> <span data-ttu-id="1995e-250">Per intercettare un'eccezione che si applica a un'attività asincrona, l'espressione `Await` si trova in un blocco `Try` del chiamante e l'eccezione viene rilevata nel blocco `Catch`.</span><span class="sxs-lookup"><span data-stu-id="1995e-250">To catch an exception that applies to an async task, the `Await` expression is in a `Try` block of the caller, and the exception is caught in the `Catch` block.</span></span>

<span data-ttu-id="1995e-251">Rimuovere il commento dalla riga `Throw New Exception` nell'esempio per illustrare la gestione delle eccezioni.</span><span class="sxs-lookup"><span data-stu-id="1995e-251">Uncomment the `Throw New Exception` line in the example to demonstrate exception handling.</span></span> <span data-ttu-id="1995e-252">L'eccezione viene rilevata nel blocco `Catch`, la proprietà `IsFaulted` dell'attività è impostata su `True`e la proprietà `Exception.InnerException` dell'attività viene impostata sull'eccezione.</span><span class="sxs-lookup"><span data-stu-id="1995e-252">The exception is caught in the `Catch` block, the task's `IsFaulted` property is set to `True`, and the task's `Exception.InnerException` property is set to the exception.</span></span>

<span data-ttu-id="1995e-253">Rimuovere il commento dalla riga `Throw New OperationCancelledException` per illustrare cosa accade quando si annulla un processo asincrono.</span><span class="sxs-lookup"><span data-stu-id="1995e-253">Uncomment the `Throw New OperationCancelledException` line to demonstrate what happens when you cancel an asynchronous process.</span></span> <span data-ttu-id="1995e-254">L'eccezione viene rilevata nel blocco `Catch` e la proprietà `IsCanceled` dell'attività è impostata su `True`.</span><span class="sxs-lookup"><span data-stu-id="1995e-254">The exception is caught in the `Catch` block, and the task's `IsCanceled` property is set to `True`.</span></span> <span data-ttu-id="1995e-255">Tuttavia, in alcune condizioni che non si applicano a questo esempio, `IsFaulted` è impostato su `True` e `IsCanceled` è impostato su `False`.</span><span class="sxs-lookup"><span data-stu-id="1995e-255">However, under some conditions that don't apply to this example, `IsFaulted` is set to `True` and `IsCanceled` is set to `False`.</span></span>

[!code-vb[csAsyncExceptions#1](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/csasyncexceptions/vb/class1.vb#1)]

### <a name="handling-multiple-exceptions-in-async-methods"></a><span data-ttu-id="1995e-256">Gestione di più eccezioni nei metodi asincroni</span><span class="sxs-lookup"><span data-stu-id="1995e-256">Handling multiple exceptions in async methods</span></span>

<span data-ttu-id="1995e-257">Il seguente esempio illustra la gestione delle eccezioni dove più attività possono restituire più eccezioni.</span><span class="sxs-lookup"><span data-stu-id="1995e-257">The following example illustrates exception handling where multiple tasks can result in multiple exceptions.</span></span> <span data-ttu-id="1995e-258">Il blocco `Try` dispone dell'espressione `Await` per l'attività che <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType> restituita.</span><span class="sxs-lookup"><span data-stu-id="1995e-258">The `Try` block has the `Await` expression for the task that <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType> returned.</span></span> <span data-ttu-id="1995e-259">L'attività viene completata quando sono state completate le tre attività a cui <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType> viene applicato.</span><span class="sxs-lookup"><span data-stu-id="1995e-259">The task is complete when the three tasks to which <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType> is applied are complete.</span></span>

<span data-ttu-id="1995e-260">Ognuna delle tre attività genera un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="1995e-260">Each of the three tasks causes an exception.</span></span> <span data-ttu-id="1995e-261">Il blocco `Catch` scorre le eccezioni presenti nella proprietà `Exception.InnerExceptions` dell'attività che `Task.WhenAll` restituita.</span><span class="sxs-lookup"><span data-stu-id="1995e-261">The `Catch` block iterates through the exceptions, which are found in the `Exception.InnerExceptions` property of the task that `Task.WhenAll` returned.</span></span>

[!code-vb[csAsyncExceptions#3](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/csasyncexceptions/vb/class1.vb#3)]

## <a name="see-also"></a><span data-ttu-id="1995e-262">Vedere anche</span><span class="sxs-lookup"><span data-stu-id="1995e-262">See also</span></span>

- <xref:Microsoft.VisualBasic.Information.Err%2A>
- <xref:System.Exception>
- [<span data-ttu-id="1995e-263">Istruzione Exit</span><span class="sxs-lookup"><span data-stu-id="1995e-263">Exit Statement</span></span>](exit-statement.md)
- [<span data-ttu-id="1995e-264">Istruzione On Error</span><span class="sxs-lookup"><span data-stu-id="1995e-264">On Error Statement</span></span>](on-error-statement.md)
- [<span data-ttu-id="1995e-265">Procedure consigliate per l'uso dei frammenti di codice</span><span class="sxs-lookup"><span data-stu-id="1995e-265">Best Practices for Using Code Snippets</span></span>](/visualstudio/ide/best-practices-for-using-code-snippets)
- [<span data-ttu-id="1995e-266">Gestione delle eccezioni</span><span class="sxs-lookup"><span data-stu-id="1995e-266">Exception Handling</span></span>](../../../standard/parallel-programming/exception-handling-task-parallel-library.md)
- [<span data-ttu-id="1995e-267">Istruzione Throw</span><span class="sxs-lookup"><span data-stu-id="1995e-267">Throw Statement</span></span>](throw-statement.md)
