---
title: Come gestire un'eccezione utilizzando try-catch - Guida per programmatori C
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: adfc53cbe4fd603ac3a6de6b9a0162320d5a2e19
ms.sourcegitcommit: 7588136e355e10cbc2582f389c90c127363c02a5
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 03/14/2020
ms.locfileid: "75712286"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="440f1-102">Come gestire un'eccezione utilizzando try/catch (Guida per programmatori C</span><span class="sxs-lookup"><span data-stu-id="440f1-102">How to handle an exception using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="440f1-103">Lo scopo di un blocco [try-catch](../../language-reference/keywords/try-catch.md) è quello di rilevare e gestire un'eccezione generata da codice in esecuzione.</span><span class="sxs-lookup"><span data-stu-id="440f1-103">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="440f1-104">Alcune eccezioni possono essere gestite in un blocco `catch` e il problema viene risolto senza che l'eccezione venga generata nuovamente. Molto spesso, invece, l'unica cosa che si possa fare è assicurarsi che venga generata l'eccezione appropriata.</span><span class="sxs-lookup"><span data-stu-id="440f1-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="440f1-105">Esempio</span><span class="sxs-lookup"><span data-stu-id="440f1-105">Example</span></span>  
 <span data-ttu-id="440f1-106">In questo esempio <xref:System.IndexOutOfRangeException> non è l'eccezione più appropriata: <xref:System.ArgumentOutOfRangeException> ha più senso per il metodo perché l'errore è causato dall'argomento `index` passato dal chiamante.</span><span class="sxs-lookup"><span data-stu-id="440f1-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="440f1-107">Commenti</span><span class="sxs-lookup"><span data-stu-id="440f1-107">Comments</span></span>  
 <span data-ttu-id="440f1-108">Il codice che genera un'eccezione è racchiuso nel blocco `try`.</span><span class="sxs-lookup"><span data-stu-id="440f1-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="440f1-109">Subito dopo viene aggiunta un'istruzione `catch` per gestire `IndexOutOfRangeException`, se si verifica.</span><span class="sxs-lookup"><span data-stu-id="440f1-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="440f1-110">Il blocco `catch` gestisce l'eccezione `IndexOutOfRangeException` e genera al suo posto l'eccezione più appropriata `ArgumentOutOfRangeException`.</span><span class="sxs-lookup"><span data-stu-id="440f1-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="440f1-111">Per offrire al chiamante quante più informazioni possibili, specificare l'eccezione originale come <xref:System.Exception.InnerException%2A> della nuova eccezione.</span><span class="sxs-lookup"><span data-stu-id="440f1-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="440f1-112">Poiché la proprietà <xref:System.Exception.InnerException%2A> è [readonly](../../language-reference/keywords/readonly.md), è necessario assegnarla nel costruttore della nuova eccezione.</span><span class="sxs-lookup"><span data-stu-id="440f1-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="440f1-113">Vedere anche</span><span class="sxs-lookup"><span data-stu-id="440f1-113">See also</span></span>

- [<span data-ttu-id="440f1-114">Guida per programmatori C#</span><span class="sxs-lookup"><span data-stu-id="440f1-114">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="440f1-115">Eccezioni e gestione delle eccezioni</span><span class="sxs-lookup"><span data-stu-id="440f1-115">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="440f1-116">Gestione delle eccezioni</span><span class="sxs-lookup"><span data-stu-id="440f1-116">Exception Handling</span></span>](./exception-handling.md)
